/**
 * Translates Dutch concepts to English using the Claude API.
 *
 * Architecture:
 *   - Reads  data/concepts.json          (Dutch, generated by build-vault.ts)
 *   - Reads  translations/cache.json     (committed to git; maps slug → translated fields + hash)
 *   - Writes data/concepts.en.json       (English, gitignored)
 *   - Writes translations/cache.json     (update only when something changed)
 *
 * Cache key: MD5 of the Dutch text fields for that concept.
 * If the Dutch source hasn't changed, no API call is made.
 *
 * Vercel: translations/cache.json is in git → Vercel never needs ANTHROPIC_API_KEY.
 * Local:  set ANTHROPIC_API_KEY in .env.local or your shell when adding new notes.
 */

import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import type { Concept } from '../lib/types';

// Load .env.local so the script works when run directly (not via Next.js)
const envLocalPath = path.join(__dirname, '../.env.local');
if (fs.existsSync(envLocalPath)) {
  for (const line of fs.readFileSync(envLocalPath, 'utf-8').split('\n')) {
    const trimmed = line.replace(/\r$/, ''); // handle Windows CRLF
    const m = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m && !process.env[m[1]]) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
}

const CACHE_FILE = path.join(__dirname, '../translations/cache.json');
const INPUT_FILE = path.join(__dirname, '../data/concepts.json');
const OUTPUT_FILE = path.join(__dirname, '../data/concepts.en.json');

interface TranslatedFields {
  titel: string;
  kern: string;
  uitleg: string;
  waarom: string;
  openVragen: string;
  verder_lezen: string;
}

interface CacheEntry extends TranslatedFields {
  hash: string;
}

type Cache = Record<string, CacheEntry>;

function sourceHash(c: Concept): string {
  const src = {
    titel: c.titel,
    kern: c.kern,
    uitleg: c.uitleg,
    waarom: c.waarom,
    openVragen: c.openVragen,
    verder_lezen: c.verder_lezen,
  };
  return crypto.createHash('md5').update(JSON.stringify(src)).digest('hex').slice(0, 12);
}

async function translateConcept(concept: Concept, client: Anthropic): Promise<TranslatedFields> {
  const input = JSON.stringify({
    titel: concept.titel,
    kern: concept.kern,
    uitleg: concept.uitleg,
    waarom: concept.waarom,
    openVragen: concept.openVragen,
    verder_lezen: concept.verder_lezen,
  });

  const response = await client.messages.create({
    model: 'claude-haiku-4-5',
    max_tokens: 3000,
    messages: [
      {
        role: 'user',
        content: `Translate this Dutch educational concept note to English.

Rules:
1. Preserve ALL HTML tags exactly as-is (<p>, <ul>, <li>, <em>, <strong>, <a href="...">, etc.)
2. Keep proper nouns as-is: names of people (Thales, Heraclitus, Russell, Penzias...), established scientific terms, Latin/Greek terms used in philosophy (arche, apeiron, logos...) — use the standard English form if one exists (e.g. "Kosmische achtergrondstraling" → "Cosmic microwave background")
3. Maintain the thoughtful, educational tone
4. The "titel" field: translate the Dutch concept name to its standard English equivalent if one exists, otherwise keep it
5. Return ONLY a valid JSON object with exactly these keys: titel, kern, uitleg, waarom, openVragen, verder_lezen

Input:
${input}`,
      },
    ],
  });

  const text = response.content[0].type === 'text' ? response.content[0].text : '{}';
  // Strip possible ```json ... ``` wrapper
  const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  return JSON.parse(cleaned) as TranslatedFields;
}

async function main() {
  if (!fs.existsSync(INPUT_FILE)) {
    console.log('⚠  data/concepts.json not found — run build-vault first');
    return;
  }

  const concepts: Concept[] = JSON.parse(fs.readFileSync(INPUT_FILE, 'utf-8'));
  const cache: Cache = fs.existsSync(CACHE_FILE)
    ? (JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8')) as Cache)
    : {};

  // Check which concepts need (re)translation
  const needsTranslation = concepts.filter((c) => {
    const entry = cache[c.slug];
    return !entry || entry.hash !== sourceHash(c);
  });

  if (needsTranslation.length > 0 && !process.env.ANTHROPIC_API_KEY) {
    console.warn(
      `⚠  ${needsTranslation.length} concept(s) need translation but ANTHROPIC_API_KEY is not set.\n` +
        '   Set it in .env.local or your shell and run: npm run translate\n' +
        '   Using cached translations for the rest.',
    );
  }

  const client = process.env.ANTHROPIC_API_KEY
    ? new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
    : null;

  let cacheUpdated = false;
  const output: Concept[] = [];

  for (const concept of concepts) {
    const hash = sourceHash(concept);
    const cached = cache[concept.slug];

    if (cached && cached.hash === hash) {
      // Cache hit — no API call needed
      const { hash: _h, ...fields } = cached;
      output.push({ ...concept, ...fields });
      continue;
    }

    if (!client) {
      // No API key — fall back to Dutch text for this concept
      output.push(concept);
      continue;
    }

    process.stdout.write(`  Translating "${concept.titel}"… `);
    try {
      const fields = await translateConcept(concept, client);
      cache[concept.slug] = { hash, ...fields };
      output.push({ ...concept, ...fields });
      cacheUpdated = true;
      console.log('✓');
    } catch (err) {
      console.log('✗ (using Dutch fallback)');
      console.error(err);
      output.push(concept);
    }
  }

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');

  if (cacheUpdated) {
    fs.mkdirSync(path.dirname(CACHE_FILE), { recursive: true });
    fs.writeFileSync(CACHE_FILE, JSON.stringify(cache, null, 2), 'utf-8');
    console.log('✓ Cache updated → translations/cache.json');
  }

  const translated = output.filter((_, i) => {
    const cached = cache[concepts[i].slug];
    return cached && cached.hash === sourceHash(concepts[i]);
  });
  console.log(`✓ ${translated.length}/${concepts.length} concept(s) in English → data/concepts.en.json`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
